name: Release Management
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: 14
    - name: Generate release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx semantic-release
